# Site settings
title: Jack Gallegos' Blog
header-img: img/home-bg.jpg
email: jgallegos@uberasch.com
copyright_name: Your/Project/Corporate Name
description: "Blog where I talk about things I am interested in"
baseurl: ""
url: "http://jeak.github.io"
twitter_username: jacko622
github_username:  deak
facebook_username:  
email_username:  jgallegos@uberasch.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
